### ISSUE TITLE
punycode encoding does not always match up with idn_to_ascii

### ISSUE THREAD

**Issue by webdevvie** [true/php-punycode#21]
Hi first of thanks for making this library. 

I think i found a bug: 
Tried to convert : άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com
Got this result from $punycode->encode($domain): 
xn--hxacdefghijklmnopqrstuvwxyz0a1a2a.com

idn_to_ascii returns this result: 
xn--hxacdefghijklmnopqrstuvw0caz0a1a2a.com

The backend domain registry provider we use indicates the encoded with this library as invalid punycode and the second(idn_to_ascii) as valid.

**Comment by ceeram** [comment]
Looks like en ancoding issue for the original string. I have added a testcase using the idn_to_ascii_result and run that through idn_to_utf8($result);

see: https://github.com/true/php-punycode/commit/6e5b1af5120bc864b4b2c6b3640e467311de2d94

**Comment by skroczek** [comment]
Funny thing. I need a little bit to understand the problem. 'σ' (sigma) is the eighteenth letter of the Greek alphabet. If it occurs at final word position it is written as 'ς'. So the domain 'άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com' is false, it should be  'άέήίΰαβγδεζηθικλμνξοπρσστυφχ.com'.
And if you add the following data to the test data provider:
```
            array(
                'άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com',
                'xn--hxacdefghijklmnopqrstuvw0caz0a1a2a.com',
            ),
```
the TrueBV\PunycodeTest::testEncodeUppercase will fail because of the mb_strtoupper($decoded, 'UTF-8') which will return 'ΆΈΉΊΰΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΣΤΥΦΧ.COM'. So mb_strtoupper converts 'ςσ' to 'ΣΣ' which is totaly right. See also https://en.wikipedia.org/wiki/Sigma

Just my two cents.

**Comment by ceeram** [comment]
I need to understand it a little better as well. I have used the correct domain in the test i added. What would be the expected result for the incorrect domain then?

**Comment by skroczek** [comment]
This is really difficult. But I found https://eurid.eu/en/news/idna2008-legacy-policy-amendment-greek-ending-sigma-german-eszett/
And after reading, I would say, if you want to be IDNA2008 compatible, that άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com and άέήίΰαβγδεζηθικλμνξοπρσστυφχ.com are two different domains and should be handled as such.
And because http://unicode.org/faq/idn.html#6 says that all uppercase characters are invalid in IDNA2008, I would say, that converting uppercase characters should not be part of this library.
But I'm not really happy with that. What do you think?

**Comment by webdevvie** [comment]
Input: άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com
Incorrect : xn--hxacdefghijklmnopqrstuvwxyz0a1a2a.com
Correct: xn--hxacdefghijklmnopqrstuvw0caz0a1a2a.com

I don't speak a lick of Greek so I have no idea why any of this is going on. 
I tested this against the .com registry test interface via our backend provider. 
It refuses to accept "Incorrect" and accepts "Correct" (above) and registers the domain with the registry. After which it is usable in their system.

I wrote a little thing to make sure I was not crazy. 
```
<?php

include("vendor/autoload.php");

use TrueBV\Punycode;

$pc = new Punycode();

$original = 'άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com';
$converted =  idn_to_ascii('άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com');
$punycodeConverted = $pc->encode($original);
$punycodeBack = $pc->decode($punycodeConverted);
$back =  idn_to_utf8($converted);

if($back == $original)
{
    echo "Same (using idn)!<br/>";
}


echo "$original<br/>$back<hr>";
if($punycodeBack == $original)
{
    echo "Same (using punycode)!<br/>";
}
echo "$original<br/>$punycodeBack<hr>";


//outputs: 
//άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com
//άέήίΰαβγδεζηθικλμνξοπρσστυφχ.com
//---------------------------------
//Same (using punycode)!
//άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com
//άέήίΰαβγδεζηθικλμνξοπρςστυφχ.com
//---------------------------------
```
Which means that punycode is actually properly converting the code to and back. But these are not accepted by the registry. idn_to_ascii is actually changing the characters. Here again I have no knowledge of Greek or exactly what the rules for the punycode notation are with regards to modifying the original version.. 

it appears that libIDN is fixing spelling mistakes ? :|

**Comment by ceeram** [comment]
Im not sure how to best handle this, idn functions are inconsistent themselves:

https://3v4l.org/ldnDD
