### ISSUE TITLE
Make encode/decode methos static?

### ISSUE THREAD

**Issue by danyaPostfactum** [true/php-punycode#7]
I am not experienced php coder, but I guess it would be better to make these methods static.
```php
Punicode::encode($host);
```

**Comment by Gamesh** [comment]
i would disagree. This would be very bad for Unit Testing. 
Basically if you use this lib as a dependency, in you software, you will not be able to to mock it to cover your code. Since PHPUnit 3.8 static methods cannot be mocked or stubbed https://phpunit.de/manual/current/en/test-doubles.html

**Comment by renan** [comment]
Indeed this is not desired, as pointed by @Gamesh.

**Comment by Gamesh** [comment]
@danyaPostfactum you can always write your wrapper class that creates Punicode as a singletone and executes it as static if you really need it to be static. For Example:
```php
class MyPunicode {
	
	private static $instance = null;
	
	public static function encode($host){
		if (!isset(self::$instance)){
			self::$instance = new Punicode();
		}
		return self::$instance->encode($host);
	}
}
```

**Comment by danyaPostfactum** [comment]
Thanks for answers. Too bad we can't make this simpler to use. Don't we like things like js `JSON.parse()` or php `DateTime::createFromFormat()`. Ok, not a big problem, thanks.

**Comment by Gamesh** [comment]
well actually DateTime::createFromFormat() is more like a factory method, that creates a DateTime object based on datetime string. It all depends on how you use libs in your code, if you do a DI, then you can call punicode in your class as simple as $this->punicode->encode(); so no need for static calls. I know it seems that shorter syntax is pretty and you don't have to create an object, but it's ugly in the long run and impossible to test.

**Comment by Spomky** [comment]
Hi,

I just want to let you know that I decided to fork this library and provide only static methods as suggested by @danyaPostfactum. See https://github.com/Spomky-Labs/php-punycode

For me, it makes sense to only provide static methods for encoding/decoding.
Projects that use this library should not have to mock the methods provided by this library, but trust on the fact that this library is correctly tested and works as expected.

Regards.

**Comment by Wirone** [comment]
I would agree with NOT making those methods static if it was argued with "they use internal property defined with constructor", but that argument with testing is totally unrelated, as @Spomky mentioned.

But even with encoding attribute it could be easily converted to static by adding optional argument to `encode` / `decode` methods. It could be backward-compatible (with `_construct` left untouched - since static methods can be called in object's context), yet more user friendly (without need to create instance each time. There is no point in forcing this to be object-oriented since it's only input/output blackbox, it does not depend on anything besides encoding.
